spring:
  application:
    name: BVHSHOP
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:postgresql://localhost:5432/VH_SHOP
    username: postgres
    password: Work@123
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: xzv7jNAmMkRSTHTJMc9LutkWCDRYZEgEEBNoDpDEE0E=
  expiration: 3600000
